# -*- coding: utf-8 -*-
"""Copy of ML_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uU7bwy3z6EuBZnu3Y83htHcH_ZCNrZu

# Machine Learning Framework for Automated Product Feedback Understanding

Step 1: Data Loading

In this step, we initialize our environment and load the dataset. We'll focus on the core columns: the review text and the numerical rating.
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

# Settings
warnings.filterwarnings('ignore')
# %matplotlib inline

# 1. Load the dataset
# The 'low_memory' option is not supported with the 'python' engine
df = pd.read_csv('data/amazonreviews.csv', on_bad_lines='skip', engine='python')

# 2. Display basic info
print(f"Dataset Shape: {df.shape}")
print("\nColumns in Dataset:")
print(df.columns.tolist())

# 3. Preview relevant columns
# For this project, 'reviews.rating' and 'reviews.text' are our primary focus
print(df[['reviews.rating', 'reviews.text']].head())

"""Step 2: Data Understanding (EDA)

Before building models, we must understand the "health" of our data. We check for missing values and analyze how users rate products.
"""

# Check for missing values in critical columns
print("Missing values in Text and Ratings:")
print(df[['reviews.text', 'reviews.rating']].isnull().sum())

# 4. Rating Distribution
plt.figure(figsize=(8, 5))
sns.countplot(x='reviews.rating', data=df, palette='viridis')
plt.title('Distribution of Product Ratings')
plt.xlabel('Rating')
plt.ylabel('Count')
plt.show()

# 5. Analyze Review Length
df['review_length'] = df['reviews.text'].astype(str).apply(len)

plt.figure(figsize=(10, 5))
sns.histplot(df['review_length'], bins=50, kde=True, color='blue')
plt.title('Distribution of Review Lengths')
plt.xlabel('Number of Characters')
plt.ylabel('Frequency')
plt.show()

print(f"Average Review Length: {df['review_length'].mean():.2f} characters")

"""Step 3: Data Cleaning

Machine learning models perform better on "clean" data. We will remove rows with missing ratings and strip away irrelevant noise like HTML tags or special characters.
"""

import re
import string

# 6. Remove missing values in target columns
df = df.dropna(subset=['reviews.rating', 'reviews.text'])

# 7. Basic Text Cleaning Function
def clean_text(text):
    text = str(text).lower() # Lowercasing
    text = re.sub(r'\[.*?\]', '', text) # Remove text in brackets
    text = re.sub(r'https?://\S+|www\.\S+', '', text) # Remove URLs
    text = re.sub(r'<.*?>+', '', text) # Remove HTML tags
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text) # Remove punctuation
    text = re.sub(r'\n', '', text) # Remove newlines
    text = re.sub(r'\w*\d\w*', '', text) # Remove words containing numbers
    return text

df['cleaned_text'] = df['reviews.text'].apply(clean_text)
print("Sample cleaned text:\n", df['cleaned_text'].iloc[0][:150])

"""Step 4: NLP Preprocessing

Now we transform the text into a format suitable for NLP. We'll remove "stopwords" (common words like 'the', 'is') and apply "lemmatization" to reduce words to their root form (e.g., "running" becomes "run").
"""

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab') # Added to resolve LookupError for punkt_tab

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_nlp(text):
    tokens = word_tokenize(text)
    # Remove stopwords and lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

df['processed_text'] = df['cleaned_text'].apply(preprocess_nlp)
print("Sample processed text:\n", df['processed_text'].iloc[0][:150])

import re
import string

# 6. Remove missing values in target columns
df = df.dropna(subset=['reviews.rating', 'reviews.text'])

# 7. Basic Text Cleaning Function
def clean_text(text):
    text = str(text).lower() # Lowercasing
    text = re.sub(r'\[.*?\]', '', text) # Remove text in brackets
    text = re.sub(r'https?://\S+|www\.\S+', '', text) # Remove URLs
    text = re.sub(r'<.*?>+', '', text) # Remove HTML tags
    text = re.sub(r'[%s]' % re.escape(string.punctuation), '', text) # Remove punctuation
    text = re.sub(r'\n', '', text) # Remove newlines
    text = re.sub(r'\w*\d\w*', '', text) # Remove words containing numbers
    return text

df['cleaned_text'] = df['reviews.text'].apply(clean_text)
print("Sample cleaned text:\n", df['cleaned_text'].iloc[0][:150])

"""Step 5: Feature Engineering

We cannot feed text directly into an ML model. We use TF-IDF (Term Frequency-Inverse Document Frequency) to convert text into a numerical matrix where each column represents a word's importance.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF with a limit on features to keep the model efficient
tfidf = TfidfVectorizer(max_features=5000, ngram_range=(1,2))
X = tfidf.fit_transform(df['processed_text'])

print(f"Feature matrix shape: {X.shape}")

import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

# Download necessary NLTK data
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab') # Added to resolve LookupError for punkt_tab

stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

def preprocess_nlp(text):
    tokens = word_tokenize(text)
    # Remove stopwords and lemmatize
    tokens = [lemmatizer.lemmatize(word) for word in tokens if word not in stop_words]
    return " ".join(tokens)

df['processed_text'] = df['cleaned_text'].apply(preprocess_nlp)
print("Sample processed text:\n", df['processed_text'].iloc[0][:150])

"""Step 6: Task 1 - Sentiment Classification

We map the numeric ratings into three sentiment categories: Negative (1-2), Neutral (3), and Positive (4-5). Then, we train a Logistic Regression model.
"""

from sklearn.svm import LinearSVC
from sklearn.model_selection import GridSearchCV, train_test_split # Added train_test_split
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import classification_report, accuracy_score # Added for evaluation metrics

# 1. Refined Feature Engineering (Improving the Vectorizer)
# We add min_df to ignore extremely rare words that act as noise
tfidf_tuned = TfidfVectorizer(max_features=10000, ngram_range=(1,3), min_df=2, stop_words='english')
X_tuned = tfidf_tuned.fit_transform(df['processed_text'])

# Add: Create the 'sentiment' column before splitting the data
def map_sentiment(rating):
    if rating >= 4: return 'Positive'
    elif rating == 3: return 'Neutral'
    else: return 'Negative'

df['sentiment'] = df['reviews.rating'].apply(map_sentiment)

# 2. Split Data
X_train, X_test, y_train, y_test = train_test_split(X_tuned, df['sentiment'], test_size=0.2, random_state=42)

# 3. Define the Model and Hyperparameter Grid
# LinearSVC is often superior to Logistic Regression for text classification
svc = LinearSVC(random_state=42, class_weight='balanced', max_iter=2000)

param_grid = {
    'C': [0.1, 1, 10],  # Penalty parameter 'C' controls the margin
    'loss': ['hinge', 'squared_hinge']
}

# 4. Use Grid Search to find the best version of the model
print("Starting Hyperparameter Tuning... (This may take a minute)")
grid_search = GridSearchCV(svc, param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# 5. Use the best model found by the Grid Search
best_model = grid_search.best_estimator_

# Optional: Calibrate the model so we can still get probability scores
final_model = CalibratedClassifierCV(best_model)
final_model.fit(X_train, y_train)

# 6. Final Evaluation
y_pred_final = final_model.predict(X_test)

print(f"\n--- Optimized Model Results ---")
print(f"Best Parameters Found: {grid_search.best_params_}")
print(f"Final Accuracy: {accuracy_score(y_test, y_pred_final):.4f}")
print("\nDetailed Classification Report:")
print(classification_report(y_test, y_pred_final))

# Update the global sentiment_model variable for the prediction function
sentiment_model = final_model
tfidf = tfidf_tuned

"""Step 7: Task 2 - Rating Prediction (Random Forest)

In this task, we try to predict the exact star rating (1 to 5) using a Random Forest Regressor.
"""

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# 12. Prepare Data for Regression - Use X_tuned for consistency with sentiment model
y_rating = df['reviews.rating']
X_train_r, X_test_r, y_train_r, y_test_r = train_test_split(X_tuned, y_rating, test_size=0.2, random_state=42)

# 13. Train Random Forest
rating_model = RandomForestRegressor(n_estimators=100, random_state=42)
rating_model.fit(X_train_r, y_train_r)

# 14. Evaluate
y_pred_r = rating_model.predict(X_test_r)
print(f"Mean Absolute Error (MAE): {mean_absolute_error(y_test_r, y_pred_r):.2f}")
print(f"Root Mean Squared Error (RMSE): {np.sqrt(mean_squared_error(y_test_r, y_pred_r)):.2f}")

"""Step 8: Task 3 - Topic Modeling (LDA)

We filter for negative reviews to identify specific "Business Issues." LDA helps us find clusters of words that represent hidden topics.
"""

from sklearn.decomposition import LatentDirichletAllocation

# 15. Filter negative reviews
negative_reviews = df[df['sentiment'] == 'Negative']['processed_text']

if len(negative_reviews) > 0:
    # Vectorize specifically for LDA (CountVectorizer is preferred for LDA)
    from sklearn.feature_extraction.text import CountVectorizer
    count_vec = CountVectorizer(max_features=1000, stop_words='english')
    lda_input = count_vec.fit_transform(negative_reviews)

    # 16. Apply LDA
    lda = LatentDirichletAllocation(n_components=3, random_state=42)
    lda.fit(lda_input)

    # 17. Show Keywords per Topic
    words = count_vec.get_feature_names_out()
    for idx, topic in enumerate(lda.components_):
        print(f"Topic #{idx+1} (Potential Issue):")
        print([words[i] for i in topic.argsort()[-10:]])
        print("-" * 20)
else:
    print("Not enough negative reviews for Topic Modeling.")

"""Step 9 & 10: Error Analysis & Business Insights

We visualize the relationship between review length and rating, and see where our model struggled.
"""

# 18. Insight: Relationship between Length and Rating
plt.figure(figsize=(10, 6))
sns.boxplot(x='reviews.rating', y='review_length', data=df)
plt.title('Review Length vs. Rating')
plt.show()

# 19. Error Analysis: Misclassified Positive as Negative
test_results = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred_final, 'Text': df.loc[y_test.index, 'reviews.text']})
misclassified = test_results[test_results['Actual'] != test_results['Predicted']]
print("Sample Misclassified Reviews:\n")
print(misclassified[['Actual', 'Predicted', 'Text']].head(3))

"""Step 11 & 12: Model Saving & Prediction Function

Finally, we save our model for future use and create a helper function for real-time inference
"""

import pickle

# 20. Save Models
with open('sentiment_model.pkl', 'wb') as f:
    pickle.dump(sentiment_model, f)
with open('tfidf_vectorizer.pkl', 'wb') as f:
    pickle.dump(tfidf, f)

# 21. Real-time Prediction Function
def predict_feedback(new_review):
    cleaned = clean_text(new_review)
    processed = preprocess_nlp(cleaned)
    vectorized = tfidf.transform([processed])

    sentiment = sentiment_model.predict(vectorized)[0]
    rating = rating_model.predict(vectorized)[0]

    return {"Sentiment": sentiment, "Predicted Rating": round(rating, 1)}

# Example Usage
print(predict_feedback("The product is okay, but the battery dies too quickly."))

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

# Download necessary NLP tools
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_and_lemma(text):
    # Remove special characters and lower the case
    text = re.sub(r'[^a-zA-Z\s]', '', str(text).lower())
    # Lemmatize and remove stopwords
    tokens = [lemmatizer.lemmatize(w) for w in text.split() if w not in stop_words]
    return " ".join(tokens)

# Apply cleaning
df['processed_text'] = df['reviews.text'].apply(clean_and_lemma)

# Create 3-way sentiment labels
# 4-5 stars = Positive, 3 stars = Neutral, 1-2 stars = Negative
df['sentiment'] = df['reviews.rating'].apply(
    lambda x: 'Positive' if x >= 4 else ('Neutral' if x == 3 else 'Negative')
)

# Save a cleaned version for your VS Code Dashboard later
df.to_csv('cleaned_amazon_data.csv', index=False)

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import accuracy_score, classification_report

# 1. Feature Engineering (using N-grams 1 to 3)
tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1,3))
X = tfidf.fit_transform(df['processed_text'])
y = df['sentiment']

# 2. Split Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# 3. Hyperparameter Tuning
param_grid = {'C': [0.1, 1, 10]}
svc = LinearSVC(class_weight='balanced', max_iter=2000)
grid = GridSearchCV(svc, param_grid, cv=5, scoring='accuracy')
grid.fit(X_train, y_train)

# 4. Calibration (to get probability/confidence scores for the UI)
best_svc = grid.best_estimator_
model = CalibratedClassifierCV(best_svc)
model.fit(X_train, y_train)

# 5. Final Accuracy Check
y_pred = model.predict(X_test)
print(f"Final Accuracy: {accuracy_score(y_test, y_pred):.4f}")

import joblib
from google.colab import files

# Save the trained model and the vectorizer
joblib.dump(model, 'sentiment_model.pkl')
joblib.dump(tfidf, 'tfidf_vectorizer.pkl')

# Download them to your computer
files.download('sentiment_model.pkl')
files.download('tfidf_vectorizer.pkl')
files.download('cleaned_amazon_data.csv')

